// generated by CommonLibrary.cmake, do not edit.

/**
 * @file include/mb/api.h
 * Defines export visibility macros for library mb.
 */

#ifndef MB_API_H
#define MB_API_H

#include <mb/defines.h>

#if defined(_MSC_VER) || defined(__declspec)
#  define MB_DLLEXPORT __declspec(dllexport)
#  define MB_DLLIMPORT __declspec(dllimport)
#else // _MSC_VER
#  define MB_DLLEXPORT
#  define MB_DLLIMPORT
#endif // _MSC_VER

#if defined(MB_STATIC)
#  define MB_API
#elif defined(MB_SHARED)
#  define MB_API MB_DLLEXPORT
#else
#  define MB_API MB_DLLIMPORT
#endif

#if defined(MB_SHARED_INL)
#  define MB_INL MB_DLLEXPORT
#else
#  define MB_INL MB_DLLIMPORT
#endif

#endif
