// generated by CommonFindPackage.cmake, do not edit.

/**
 * @file include/mb/defines.h
 * Includes compile-time defines of MB.
 */

#ifndef MB_DEFINES_H
#define MB_DEFINES_H

#ifdef __APPLE__
#  include <mb/definesDarwin.h>
#elif defined (__linux__)
#  include <mb/definesLinux.h>
#elif defined (_WIN32)
#  include <mb/definesWin32.h>
#else
#  error Unknown OS
#endif

#endif
