// generated by CommonFindPackage.cmake, do not edit.

#ifndef MB_DEFINES_Linux_H
#define MB_DEFINES_Linux_H

#ifndef Linux
#  define Linux 1
#endif
#ifndef MB_USE_CXX11
#  define MB_USE_CXX11 1
#endif
#ifndef MB_LITTLEENDIAN
#  define MB_LITTLEENDIAN 1
#endif
#ifndef MB_COMPUTE_SHADERS
#  define MB_COMPUTE_SHADERS 1
#endif
#ifndef MB_GEOMETRY_SHADERS
#  define MB_GEOMETRY_SHADERS 1
#endif
#ifndef MB_TESSELATION_SHADERS
#  define MB_TESSELATION_SHADERS 1
#endif
#ifndef MB_SUBPROGRAMS
#  define MB_SUBPROGRAMS 1
#endif
#ifndef MB_OCC_QUERY
#  define MB_OCC_QUERY 1
#endif
#ifndef MB_TRANSFORM_FEEDBACK
#  define MB_TRANSFORM_FEEDBACK 1
#endif
#ifndef MB_USE_EIGEN3
#  define MB_USE_EIGEN3 1
#endif
#ifndef MB_USE_OPENGL
#  define MB_USE_OPENGL 1
#endif
#ifndef MB_USE_GLEW
#  define MB_USE_GLEW 1
#endif
#ifndef MB_USE_BOOST
#  define MB_USE_BOOST 1
#endif
#ifndef MB_USE_GLFW3
#  define MB_USE_GLFW3 1
#endif
#ifndef MB_USE_FREEIMAGE
#  define MB_USE_FREEIMAGE 1
#endif

#endif
