// generated by CommonLibrary.cmake, do not edit.

#include <mb/version.h>
#include <sstream>

namespace mb
{

int Version::getMajor()
{
    return MB_VERSION_MAJOR;
}

int Version::getMinor()
{
    return MB_VERSION_MINOR;
}

int Version::getPatch()
{
    return MB_VERSION_PATCH;
}

int Version::getABI()
{
    return MB_VERSION_ABI;
}

std::string Version::getString()
{
    std::ostringstream version;
    version << getMajor() << '.' << getMinor() << '.' << getPatch();
    return version.str();
}

int Version::getRevision()
{
    return MB_VERSION_REVISION;
}

std::string Version::getRevString()
{
    std::ostringstream version;
    version << getString() << '.' << std::hex << getRevision() << std::dec;
    return version.str();
}

}
