# Generated by CommonPackageConfig.cmake

# if target already exists (subproject build), no need to find any dependencies
if(TARGET MB_ALIAS)
  list(APPEND CMAKE_MODULE_PATH "/home/crodriguez/Desktop/monkeybrushplusplus/build2/share/MB/CMake")
else()
  list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")

  # find dependent libraries which provide dependent targets
  include(CMakeFindDependencyMacro)
  find_dependency(OpenGL)
  find_dependency(GLEW)
  find_dependency(GLFW3)
  find_dependency(FreeImage)
  find_dependency(Eigen3)

  if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/MBTargets.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/MBTargets.cmake")
  endif()
endif()

if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/options.cmake")
  include("${CMAKE_CURRENT_LIST_DIR}/options.cmake")
endif()
