# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget mb)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target mb
add_library(mb SHARED IMPORTED)

set_target_properties(mb PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_alias_templates;cxx_nullptr;cxx_override;cxx_final;cxx_noexcept"
  INTERFACE_INCLUDE_DIRECTORIES "/home/crodriguez/Desktop/monkeybrushplusplus;/home/crodriguez/Desktop/monkeybrushplusplus/build2/include;/home/crodriguez/Desktop/monkeybrushplusplus/build2"
  INTERFACE_LINK_LIBRARIES "-lX11;-lXi;-lXrandr;-lXxf86vm;-lXinerama;-lXcursor;-lrt;-lm;-pthread;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLEW.so;/usr/lib/x86_64-linux-gnu/libfreeimage.so;/usr/lib/libglfw3.a"
)

# Import target "mb" for configuration "Release"
set_property(TARGET mb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(mb PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/crodriguez/Desktop/monkeybrushplusplus/build2/lib/libmb.so.1.9.2"
  IMPORTED_SONAME_RELEASE "libmb.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
