set(MB_MATURITY "EP")
set(MB_DESCRIPTION "MonkeyBrush++")
set(MB_GIT_ROOT_URL "git@github.com:maldicion069/monkeybrushplusplus.git")
set(MB_PACKAGE_URL "")
set(MB_CI_URL "git@travis-ci.org:maldicion069/monkeybrushplusplus")
set(MB_CI_PNG "git@travis-ci.org:maldicion069/monkeybrushplusplus.png")
set(MB_ISSUES_URL "git@github.com:maldicion069/monkeybrushplusplus/issues")
